export enum NotificationType {
  JOB_REQUEST = "JOB_REQUEST",
  JOB_ACCEPTED = "JOB_ACCEPTED",
  JOB_REJECTED = "JOB_REJECTED",
  DRIVER_ASSIGNED = "DRIVER_ASSIGNED",
  DRIVER_ARRIVED = "DRIVER_ARRIVED",
  JOB_STARTED = "JOB_STARTED",
  JOB_COMPLETED = "JOB_COMPLETED",
  JOB_CANCELLED = "JOB_CANCELLED",

  PAYMENT_RECEIVED = "PAYMENT_RECEIVED",

  DRIVER_ONLINE = "DRIVER_ONLINE",
  DRIVER_OFFLINE = "DRIVER_OFFLINE",

  VEHICLE_ASSIGNED = "VEHICLE_ASSIGNED",
  VEHICLE_MAINTENANCE = "VEHICLE_MAINTENANCE",
  VEHICLE_DOCUMENT_EXPIRY = "VEHICLE_DOCUMENT_EXPIRY",

  LICENSE_EXPIRY = "LICENSE_EXPIRY",

  SYSTEM = "SYSTEM"
}

export enum NotificationPriority {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL"
}