export enum ServiceType {
  CAR_TOWING = "CAR_TOWING",

  BOX_RECOVERY = "BOX_RECOVERY",

  BIKE_TOWING = "BIKE_TOWING",

  JUMP_START = "JUMP_START",

  BATTERY_REPLACEMENT = "BATTERY_REPLACEMENT",

  FLAT_TIRE_REPLACEMENT = "FLAT_TIRE_REPLACEMENT",

  FUEL_DELIVERY = "FUEL_DELIVERY",
}